//USER REDUCER TYPE
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER'

//UI RDUCER TYPE
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const STOP_LOADING = 'STOP_LOADING'
//DATA REDUCER TYPE
export const GET_TERMINAL = 'GET_TERMINAL'
export const GET_ROUTES = 'GET_ROUTES'
export const GET_TRIP = 'GET_TRIPS'
export const DETAILS = 'DETAILS'
export const BOOKINGDETAILS = 'BOOKINGDETAILS'
